# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1d29b71f4cfb8d46ad64be5b7991308436b449c0cf37b7b52edb1dbc28727bf3abc7caf588ea376b3da8a36bcdd4872d8b596d15faa3ffe7166f8c6049565c

test:
  secret_key_base: 01bef1f3d136d6cecabe8feeab9dc4e73c9d03b0c0f0e609f40753b90b6e1cc2faf97917835b50754ac74a793b16bd5e19dab16327ca388e35cbcfcca250c382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
